### ISSUE TITLE
Error, no records were correctly parsed from filtered.fastq

### ISSUE THREAD

**Issue by NickPanyushev** [mobilomics/TEcandidates#12]
Hello, @bvaldebenitom ! 

After I launch the TEcandidates on the test data, I tried to use it on my real data with paired-end reads. But it failed with the error: 

```
Error, no records were correctly parsed from /home/common/adonin.ls/TEcandidates_urchin/candidateTE_analysis_coverage-0.3_length-900_N-1/SRR8863027_filtered_2.fastqError, no records were correctly parsed from /home/common/adonin.ls/TEcandidates_urchin/candidateTE_analysis_coverage-0.3_length-900_N-1/SRR8863027_filtered_1.fastqThread 1 terminated abnormally: Error, cmd: seqtk-trinity seq -A -R 1  /home/common/adonin.ls/TEcandidates_urchin/candidateTE_analysis_coverage-0.3_length-900_N-1/SRR8863027_filtered_1.fastq >> left.fa died with ret 1280 at /home/common/adonin.ls/.programs/trinityrnaseq-v2.11.0/util/insilico_read_normalization.pl line 793.
```

It seems that the program cannot properly produce filtered fastqs from aligned bam files, because filtered.fastq are empty. 
```
-rw-r--r--. 1 adonin.ls calccommon 619M янв 17 20:14 SRR8863028.bam
-rw-r--r--. 1 adonin.ls calccommon  635 янв 17 20:14 SRR8863028.bt2_summary
-rw-r--r--. 1 adonin.ls calccommon    0 янв 17 20:14 SRR8863028_filtered_1.fastq
-rw-r--r--. 1 adonin.ls calccommon    0 янв 17 20:14 SRR8863028_filtered_2.fastq
```
And all fastq files were well aligned, here is the example of the alignment summary file

```
7176713 reads; of these:
  7176713 (100.00%) were paired; of these:
    3755295 (52.33%) aligned concordantly 0 times
    2491518 (34.72%) aligned concordantly exactly 1 time
    929900 (12.96%) aligned concordantly >1 times
    ----
    3755295 pairs aligned concordantly 0 times; of these:
      552958 (14.72%) aligned discordantly 1 time
    ----
    3202337 pairs aligned 0 times concordantly or discordantly; of these:
      6404674 mates make up the pairs; of these:
        3345090 (52.23%) aligned 0 times
        1545843 (24.14%) aligned exactly 1 time
        1513741 (23.63%) aligned >1 times
76.69% overall alignment rate
```
 
Here are the [launch script for slurm](https://github.com/mobilomics/TEcandidates/files/5918266/TEcandidates_launch.sh.txt), the full [stdout](https://github.com/mobilomics/TEcandidates/files/5918241/TEcandidates_urchin.log) and [stderr](https://github.com/mobilomics/TEcandidates/files/5918244/TEcandidates_urchin.err.log)  files for reference.

This is the [code](https://github.com/mobilomics/TEcandidates/files/5918260/TEcandidates.sh.txt) I launched. It is mainly TE_candidates 2.0.3.sh but with several uncommented lines. Also, I've commented out the /usr/bin/time invocation because I couldn't make it work on the test data.  

Thank you very much in advance!

**Comment by NickPanyushev** [comment]
Upd: 

I've found the source of this bug. TEcandidates reqiures the extensiion of repeat annotation file to be **exactly .gff3** Of course, it will accept .gff or any another extension but this [line](https://github.com/mobilomics/TEcandidates/blob/b8a30be5e8cbd7c314ac74924e3cbddff3882005/TEcandidates_v2.0.3.sh#L234)
`bedFile=${TEannotation/.gff3/.bed}`
 will yield the incorrect result. Instead of creating the new bed file it rewrites the original repeat annotation and TEcandidates fails with the error. 

The best solution of this issue could be adding of the check of the file extension before running the main script, I suppose. Or it could be clearly mentioned in the documentation. 
@bvaldebenitom, could you handle this?

**Comment by bvaldebenitom** [comment]
@NickPanyushev thanks for the update, and the suggestion. We are in holidays over here, so apologies for the delay in replying. A new version of the tool will go live on Wednesday, having many of these bug fixes.

Please let me know if I can help in any further way!

**Comment by bvaldebenitom** [comment]
@NickPanyushev the new version with bug fixes thanks to your feedback is [now available](https://github.com/mobilomics/TEcandidates/releases/tag/v2.0.5)
